title: Développement web sur mes projets personnels
author: Sylvain Dethier
email: dethiersylvain@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles sur le développement web de mes projets personnels.

# social links
twitter_username: sylvaindethier # DO NOT include the @ character, or else the build will fail!
github_username:  sylvaindethier # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
