title: Projets personnels en développement web
author: Sylvain Dethier
email: dethiersylvain@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Articles sur mes projets personnels en développement web.

# social links
twitter_username: sylvaindethier # DO NOT include the @ character, or else the build will fail!
github_username:  sylvaindethier # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
